### ISSUE TITLE
"Contract transaction couldn't be found after 50 blocks"

### ISSUE THREAD

**Issue by bortzmeyer** [rakeshbs/solidity_compiler_helper#2]
I installed a contract o, the Modern testnet with solc_helper and everything was fine but the same contract, on the main net, created a loop, creating many instances of the contract and burning a lot of ethers.

In the end, the error message from the console was:

```
> loadScript('/home/stephane/src/Solidity/soleau/soleau_compiled.js')
null
Contract transaction send: TransactionHash: 0x10fc35fdf0e8285508404069a59dd4f8477878c2215b4a103c62df97b083ac09 waiting to be mined...
Compiled Object : SoleauCompiled
Contract : SoleauContract
Contract Instance : Soleau
true
> 
> Error: Contract transaction couldn't be found after 50 blocks
```

You can see the many creations [on any explorer](http://etherscan.io/address/0x22e1472e3486dd72f4d65e1f6ca7b2f49205fc26)

**Comment by rakeshbs** [comment]
was there any bug within your contract? This helper simply deploys the contract using the web3 api in geth.

**Comment by bortzmeyer** [comment]
A bug in the contract could cause that? The contract does install properly on the testnet.

**Comment by bortzmeyer** [comment]
The bug may be in geth itself? https://github.com/ethereum/go-ethereum/issues/2764

**Comment by rakeshbs** [comment]
Did you try deploying the contract manually through geth?

**Comment by bortzmeyer** [comment]
Explanation found: it was not related to solc_helper, I close the ticket https://github.com/ethereum/go-ethereum/issues/2764#issuecomment-231584482
